### ISSUE TITLE
Feature data popups do not work in Firefox (44.0.2)

### ISSUE THREAD

**Issue by jsvrcek** [ROGUE-JCTD/MapLoom#185]
Tested using a random layer on the demo server (http://demo.geoshape.org/maps/new?layer=geonode%3Acd09).

Clicking on a feature in chrome will display information (and media assets), however nothing happens in Firefox.

**Comment by davidpinheiro** [comment]
Same bug as #184

**Comment by richard3d** [comment]
This issue is resolved and tested at least for latest Firefox (currently version 44). There was an error in the way way feature info was processed as well in the source and this has been resolved. Note: This issue pertains to demo.geoshape.org which is not guaranteed to be running the latest build of MapLoom at all times.

**Comment by garnertb** [comment]
Closing based on comments.
